Fix `An argument named "contact_method" is not expected here.` error:
```
=== RUN   TestAccPagerDutyUserNotificationRuleContactMethod_Basic
    resource_pagerduty_user_notification_rule_test.go:20: Step 1/3 error: Error running pre-apply refresh: exit status 1

        Error: Insufficient contact_method blocks

          on terraform_plugin_test.tf line 2, in resource "pagerduty_user_notification_rule" "foo":
           2: resource "pagerduty_user_notification_rule" "foo" {

        At least 1 "contact_method" blocks are required.

        Error: Unsupported argument

          on terraform_plugin_test.tf line 7, in resource "pagerduty_user_notification_rule" "foo":
           7:   contact_method = {

        An argument named "contact_method" is not expected here. Did you mean to
        define a block of type "contact_method"?
--- FAIL: TestAccPagerDutyUserNotificationRuleContactMethod_Basic (0.68s)
```